server:
  port: 8081

spring:
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    name: vueblog

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization